title: 服务状态
name: butter_status
description: ""
defaultLocale: zh-cn
baseUrl: "https://status.butterapis.com"
locales:
  - code: zh-cn
    iso: zh-CN
    name: 中文
    file: zh-cn.json
content:
  frontMatterFormat: yaml
  systems:
    - cdn
    - account
    - user
    - post
    - template
    - shop
    - feed
